name: CI Pipeline

# Sự kiện trigger pipeline
on:
  push:         # Chạy khi có hành động push lên repository
    branches:
      - main     # Chỉ trigger khi push lên nhánh 'main'
  pull_request:  # Chạy khi có pull request tạo vào nhánh 'main'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

      - name: Run tests
        run: |
          echo "Running tests..."
          # Thêm lệnh để chạy bài kiểm tra của bạn ở đây, ví dụ:
          # pytest
  test:
    runs-on: ubuntu-latest
    
    steps:

      - name: Run tests
        run: |
          echo "Running tests..."
          # Thêm lệnh để chạy bài kiểm tra của bạn ở đây, ví dụ:
          # pytest
  noti:
    runs-on: ubuntu-latest
    
    steps:

      - name: Run tests
        run: |
          echo "Running tests..."
          # Thêm lệnh để chạy bài kiểm tra của bạn ở đây, ví dụ:
          # pytest