name: CI Pipeline

# event trigger pipeline
on:
  workflow_dispatch:  # trigger manual

jobs:
  Smoke:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 18.14.0
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.0'

      - name: Setup environment
        run: npm install

      - name: Run test case
        id: error 
        run: eval env=ci_chrome_stag npm run f L-01 || FAILED=true 

      # - name: Send failure notification to Lark
      #   if: failure() 
      #   run: node src/core/messageToLark.js "$ERROR_MESSAGE"

      - name: Upload test report
        uses: actions/upload-artifact@v4  
        with:
          name: allure-results 
          path: reports/allure-results
          

  deploy_report:
    runs-on: self-hosted
    needs: Smoke 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 18.14.0
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.0'

      - name: Download test report
        uses: actions/download-artifact@v4
        with:
          name: allure-results 
          path: reports/allure-results

      - name: Generate Allure Report
        run: |
          npm install
          allure generate ./reports/allure-results --clean

      - name: Deploy to Netlify
        run: |
          npm install -g netlify-cli
          netlify deploy --prod --dir=allure-report --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  send_notifications_to_lark:
    runs-on: self-hosted
    needs: [Smoke, deploy_report]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      - name: Install dependencies
        run: npm install

      - name: Send notifications
        run: |
          echo "Send notifications................................................................"
          node src/core/messageToLark.js