name: CI Pipeline

# Sự kiện trigger pipeline
on:
  push:         # Chạy khi có hành động push lên repository
    branches:
      - main     # Chỉ trigger khi push lên nhánh 'main'
  pull_request:  # Chạy khi có pull request tạo vào nhánh 'main'
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Chạy trên máy ảo macOS mới nhất

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Kiểm tra mã nguồn từ repository

      - name: Set up Node.js 18.12.1
        uses: actions/setup-node@v3  # Cài đặt Node.js
        with:
          node-version: '18.12.1'  # Chỉ định phiên bản Node.js bạn muốn cài đặt

      - name: Install dependencies
        run: npm install  # Chạy npm install để cài đặt các phụ thuộc từ package.json

      - name: Run tests
        run: |
          echo "Regression Testing ................................................"