name: CI Pipeline

# Sự kiện trigger pipeline
on:
  workflow_dispatch:  # Cho phép trigger thủ công

jobs:
  Smoke:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      - name: Install dependencies
        run: npm install

      - name: Run test case
        id: error  # Đặt ID cho bước này để tham chiếu đến sau
        run: eval env=ci_\"chrome\"_\"stag\" npm run f L-01 || FAILED=true  # Lệnh chạy test, nếu lỗi thì tiếp tục

      # - name: Send failure notification to Lark
      #   if: failure()  # Chỉ chạy bước này khi job thất bại
      #   run: node src/core/messageToLark.js "$ERROR_MESSAGE"  # Truyền lỗi vào thông báo

      - name: Upload test report
        uses: actions/upload-artifact@v4  # Upload report làm artifact
        with:
          name: allure-results  # Tên artifact (có thể tuỳ chỉnh)
          path: reports/allure-results
          

  deploy_report:
    runs-on: self-hosted
    needs: Smoke  # Chỉ chạy sau khi Smoke thành công

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download test report
        uses: actions/download-artifact@v4
        with:
          name: allure-results  # Tên của artifact đã upload
          path: reports/allure-results

      - name: Generate Allure Report
        run: |
          npm install
          allure generate allure-results --clean -o allure-report

      - name: Deploy to Netlify
        run: |
          npm install -g netlify-cli
          netlify deploy --prod --dir=allure-report --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  send_notifications_to_lark:
    runs-on: self-hosted
    needs: [Smoke, deploy_report]  # Chỉ chạy sau khi Smoke và deploy_report thành công

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      - name: Install dependencies
        run: npm install

      - name: Send notifications
        run: |
          echo "Send notifications................................................................"
          node src/core/messageToLark.js