name: CI Pipeline

on: [push]

stages:
  - build
  - test
  - report
  - send-report
  - notify-failure

build:
  stage: build
  script:
    - echo "Building the project..."
    - # Thêm lệnh build của bạn vào đây

test:
  stage: test
  script:
    - echo "Running tests..."
    - # Thêm lệnh chạy test của bạn vào đây

report:
  stage: report
  script:
    - echo "Generating the report..."
    - # Thêm lệnh tạo báo cáo của bạn vào đây

send-report:
  stage: send-report
  script:
    - echo "Sending the report..."
    - # Thêm lệnh gửi báo cáo của bạn vào đây

notify-failure:
  stage: notify-failure
  script:
    - echo "Notifying failure..."
    - # Thêm lệnh thông báo lỗi của bạn vào đây
  when: on_failure  # Chỉ chạy khi pipeline thất bại