name: CI Pipeline

# Sự kiện trigger pipeline
on:
  workflow_dispatch:  # Cho phép trigger thủ công

jobs:
  Smoke:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      - name: Install dependencies
        run: npm install

      - name: Run test case
        run: npm run f L-01

      - name: Upload test report
        uses: actions/upload-artifact@v3  # Upload report làm artifact
        with:
          name: allure-report  # Tên của artifact
          path: reports/allure-results    # Đường dẫn tới file hoặc thư mục bạn muốn upload

  deploy_report:
    runs-on: macos-latest
    needs: Smoke  # Chỉ chạy sau khi Smoke thành công

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      - name: Install dependencies
        run: npm install

      - name: Download test report
        uses: actions/download-artifact@v3  # Tải artifact từ job `Smoke`
        with:
          name: allure-report   # Tên của artifact cần tải
      - name: Deploy report
          run: |
              echo "Deploying report..."
              cat reports/allure-results/favicon.ico  # Hiển thị nội dung report (demo)

  send_notifications_to_lark:
    runs-on: macos-latest
    needs: [Smoke, deploy_report]  # Chỉ chạy sau khi Smoke và deploy_report thành công

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      - name: Install dependencies
        run: npm install

      - name: Send notifications
        run: |
          echo "Send notifications................................................................"
          node src/core/messageToLark.js